# Generated by Django 5.2.17 on 2026-09-17 20:20

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guests", "0003_gin_index_guest_profile_name"),
        (
            "properties",
            "0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more",
        ),
        ("rooms", "0004_remove_roomstateevent_room_state_event_valid_transition_and_more"),
        ("tenants", "0002_tenantsettings_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reservation_ref", models.CharField(max_length=32)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("held", "Held"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("converted", "Converted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("direct", "Direct")], default="direct", max_length=16
                    ),
                ),
                ("hold_expiry_at", models.DateTimeField(blank=True, null=True)),
                ("price_snapshot", models.JSONField(blank=True, default=dict)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="guests.guestprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reservations",
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reservations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
            },
        ),
        migrations.CreateModel(
            name="ReservationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveSmallIntegerField()),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("price_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lines",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reservation_lines",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_line",
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                condition=models.Q(("status__in", ["held", "awaiting_payment"])),
                fields=["property", "status", "hold_expiry_at"],
                name="reservation_ix_sweep_hot_path",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["guest_profile"], name="reservation_ix_guest"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["created_at"], name="reservation_ix_created"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reservation_ref"), name="reservation_uq_tenant_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "held", "awaiting_payment", "converted", "expired", "cancelled"],
                    )
                ),
                name="reservation_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hold_expiry_at__isnull", True),
                    ("hold_expiry_at__gt", models.F("created_at")),
                    _connector="OR",
                ),
                name="reservation_hold_expiry_after_created",
            ),
        ),
        migrations.AddIndex(
            model_name="reservationline",
            index=models.Index(fields=["reservation"], name="reservation_line_ix_resv"),
        ),
        migrations.AddConstraint(
            model_name="reservationline",
            constraint=models.UniqueConstraint(
                fields=("reservation", "line_no"), name="reservation_line_uq_reservation_lineno"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("departure_date__gt", models.F("arrival_date"))),
                name="reservation_line_departure_after_arrival",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="reservation_line_quantity_positive"
            ),
        ),
    ]
