# Generated by Django 5.2.17 on 2026-09-04 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more'),
        ('rooms', '0004_remove_roomstateevent_room_state_event_valid_transition_and_more'),
        ('tenants', '0002_tenantsettings_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('base_rate_minor_units', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('sellable', models.BooleanField(default=True)),
                ('policy_refs', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_plans', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_plans', to='rooms.roomtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_plans', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('absolute', 'Absolute'), ('percent', 'Percent')], max_length=16)),
                ('adjustment_minor_units', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_overrides', to='tenants.tenant')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='overrides', to='pricing.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='RateModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('modifier_type', models.CharField(choices=[('season', 'Season'), ('weekend', 'Weekend'), ('holiday', 'Holiday'), ('long_stay', 'Long stay'), ('corporate', 'Corporate')], max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_modifiers', to='tenants.tenant')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modifiers', to='pricing.rateplan')),
            ],
        ),
        migrations.AddIndex(
            model_name='rateplan',
            index=models.Index(fields=['property', 'status'], name='pricing_rat_propert_3f4f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='rateplan',
            index=models.Index(fields=['room_type', 'status'], name='pricing_rat_room_ty_9fdafd_idx'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'retired'])), name='rate_plan_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate_minor_units__gte', 0)), name='rate_plan_base_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='rate_plan_currency_iso3'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='rate_plan_uq_property_code'),
        ),
        migrations.AddIndex(
            model_name='rateoverride',
            index=models.Index(fields=['rate_plan', 'start_date'], name='pricing_rat_rate_pl_78692c_idx'),
        ),
        migrations.AddConstraint(
            model_name='rateoverride',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_type__in', ['absolute', 'percent'])), name='rate_override_valid_adjustment_type'),
        ),
        migrations.AddConstraint(
            model_name='rateoverride',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_minor_units', 0), _negated=True), name='rate_override_adjustment_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='rateoverride',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='rate_override_end_on_or_after_start'),
        ),
        migrations.AddIndex(
            model_name='ratemodifier',
            index=models.Index(fields=['rate_plan', 'modifier_type'], name='pricing_rat_rate_pl_e4364b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratemodifier',
            constraint=models.CheckConstraint(condition=models.Q(('modifier_type__in', ['season', 'weekend', 'holiday', 'long_stay', 'corporate'])), name='rate_modifier_valid_type'),
        ),
    ]
