# Generated by Django 5.2.17 on 2026-08-09 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='May access the platform admin site.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('deactivated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user account',
                'verbose_name_plural': 'user accounts',
                'db_table': 'user_account',
            },
            managers=[
                ('objects', apps.accounts.managers.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(condition=models.Q(('status', 'deactivated'), _negated=True), fields=['status'], name='user_account_ix_active_status'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['created_at'], name='user_account_ix_created'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'locked', 'deactivated'])), name='user_account_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(condition=models.Q(('failed_attempts__gte', 0)), name='user_account_failed_attempts_ge_zero'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user_account_id', 'status'], name='membership_ix_user_status'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant_id', 'status'], name='membership_ix_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'revoked'])), name='membership_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant_id', 'user_account_id'), name='membership_uq_tenant_user'),
        ),
    ]
