# Generated by Django 5.2.17 on 2026-08-09 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'role',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='role_ix_tenant_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'retired'])), name='role_status_valid'), models.UniqueConstraint(fields=('tenant_id', 'name'), name='role_uq_tenant_name')],
            },
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='accounts.role')),
            ],
            options={
                'db_table': 'membership_role',
                'constraints': [models.UniqueConstraint(fields=('membership', 'role'), name='membership_role_uq_pair')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.role')),
            ],
            options={
                'db_table': 'invitation',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['tenant_id', 'status', 'expires_at'], name='invitation_pending_tenant_exp')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'expired', 'revoked'])), name='invitation_status_valid'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='invitation_expiry_after_created')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('permission_code', models.CharField(max_length=80)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role')),
            ],
            options={
                'db_table': 'role_permission',
                'indexes': [models.Index(fields=['permission_code'], name='role_permission_ix_code')],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission_code'), name='role_permission_uq_role_code')],
            },
        ),
    ]
