# Generated by Django 5.2.17 on 2026-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_membershiprole_invitation_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='locked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
