# Generated by Django 5.2.17 on 2026-08-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_locked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('totp', 'TOTP'), ('webauthn', 'WebAuthn')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('secret_key', models.CharField(editable=False, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('removed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_device',
                'constraints': [models.CheckConstraint(condition=models.Q(('device_type__in', ['totp', 'webauthn'])), name='mfa_device_type_valid'), models.CheckConstraint(condition=models.Q(('verified_at__isnull', False), ('removed_at__isnull', True), _connector='OR'), name='mfa_device_verified_or_removed'), models.UniqueConstraint(fields=('user_account', 'device_type', 'name'), name='mfa_device_uq_user_type_name')],
            },
        ),
    ]
