# Generated by Django 5.2.17 on 2026-08-10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='property_groups', to='tenants.tenant')),
                ('name', models.CharField(max_length=128)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='properties', to='tenants.tenant')),
                ('property_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertygroup')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='draft', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=64)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings', to='tenants.tenant')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings', to='properties.property')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='floors', to='tenants.tenant')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='floors', to='properties.building')),
                ('name', models.CharField(max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facilities', to='tenants.tenant')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facilities', to='properties.property')),
                ('facility_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='media_assets', to='tenants.tenant')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='media_assets', to='properties.property')),
                ('object_key', models.CharField(max_length=256, unique=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('floor_plan', 'Floor Plan'), ('virtual_tour', 'Virtual Tour')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='propertygroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_property_group_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_property_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'active', 'deactivated'])), name='property_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_building_code_per_property'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_floor_name_per_building'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('property', 'facility_type', 'name'), name='unique_facility_per_property_and_type'),
        ),
        migrations.AddIndex(
            model_name='propertygroup',
            index=models.Index(fields=['tenant'], name='properties_p_tenant_1d4a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'status'], name='properties_p_tenant_2f3e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties_p_latitud_3c2d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['property'], name='properties_b_property_4f5e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['building'], name='properties_f_building_5a6b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['property'], name='properties_f_property_6b7c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['property', 'kind'], name='properties_m_property_7c8d9e_idx'),
        ),
    ]