# Generated by Django 5.2.17 on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # PropertyGroup RLS
                """
                CREATE POLICY property_group_tenant_isolation_policy ON properties_propertygroup
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # Property RLS
                """
                CREATE POLICY property_tenant_isolation_policy ON properties_property
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # Building RLS
                """
                CREATE POLICY building_tenant_isolation_policy ON properties_building
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # Floor RLS
                """
                CREATE POLICY floor_tenant_isolation_policy ON properties_floor
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # Facility RLS
                """
                CREATE POLICY facility_tenant_isolation_policy ON properties_facility
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # MediaAsset RLS
                """
                CREATE POLICY mediaasset_tenant_isolation_policy ON properties_mediaasset
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
            ],
            reverse_sql=[
                "DROP POLICY IF EXISTS property_group_tenant_isolation_policy ON properties_propertygroup;",
                "DROP POLICY IF EXISTS property_tenant_isolation_policy ON properties_property;",
                "DROP POLICY IF EXISTS building_tenant_isolation_policy ON properties_building;",
                "DROP POLICY IF EXISTS floor_tenant_isolation_policy ON properties_floor;",
                "DROP POLICY IF EXISTS facility_tenant_isolation_policy ON properties_facility;",
                "DROP POLICY IF EXISTS mediaasset_tenant_isolation_policy ON properties_mediaasset;",
            ],
        ),
    ]