# Generated by Django 5.2.17 on 2026-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rls'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='building',
            new_name='properties__propert_80482c_idx',
            old_name='properties_b_property_4f5e6d_idx',
        ),
        migrations.RenameIndex(
            model_name='facility',
            new_name='properties__propert_db4c3e_idx',
            old_name='properties_f_property_6b7c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='floor',
            new_name='properties__buildin_e4dc7f_idx',
            old_name='properties_f_building_5a6b7c_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='properties__propert_cd2dd0_idx',
            old_name='properties_m_property_7c8d9e_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__tenant__b1580b_idx',
            old_name='properties_p_tenant_2f3e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__latitud_6eb2b0_idx',
            old_name='properties_p_latitud_3c2d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='propertygroup',
            new_name='properties__tenant__762bb9_idx',
            old_name='properties_p_tenant_1d4a2b_idx',
        ),
    ]
