# Generated by Django 5.2.17 on 2026-09-17, then hand-edited (M7, E7):
# ``AvailabilitySlot`` is wrapped in SeparateDatabaseAndState so PostgreSQL
# gets the REAL partitioned table (PARTITION BY RANGE(business_date), a
# composite PK including the partition key, generated ``remaining``, every
# CHECK/UNIQUE/index, and the starter partitions) while SQLite gets the
# ordinary, non-partitioned Django table Django would have created anyway —
# see the module docstring on ``apps/availability/models.py`` and
# ``apps/availability/partitioning.py`` for the full rationale.
#
# Every other model in this app (InventoryBlock, InventoryBlockNight,
# ChannelAllocation) is an untouched, normal CreateModel — no partitioning
# need for those tables.

from datetime import timedelta

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

from apps.availability import partitioning

# ---------------------------------------------------------------------------
# AvailabilitySlot: state (used by the ORM on both backends) vs. real DDL.
# ---------------------------------------------------------------------------

_AVAILABILITY_SLOT_STATE = migrations.CreateModel(
    name="AvailabilitySlot",
    fields=[
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
            "channel",
            models.CharField(choices=[("direct", "Direct")], default="direct", max_length=16),
        ),
        ("business_date", models.DateField()),
        ("id", models.BigIntegerField(editable=False)),
        ("total_units", models.PositiveIntegerField()),
        ("sold", models.PositiveIntegerField(default=0)),
        ("reserved", models.PositiveIntegerField(default=0)),
        ("blocked", models.PositiveIntegerField(default=0)),
        ("out_of_service", models.PositiveIntegerField(default=0)),
        (
            "remaining",
            models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("total_units"), "-", models.F("sold")
                            ),
                            "-",
                            models.F("reserved"),
                        ),
                        "-",
                        models.F("blocked"),
                    ),
                    "-",
                    models.F("out_of_service"),
                ),
                output_field=models.IntegerField(),
            ),
        ),
        (
            "pk",
            models.CompositePrimaryKey(
                "business_date", "id", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        (
            "property",
            models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="availability_slots",
                to="properties.property",
            ),
        ),
        (
            "room_type",
            models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="availability_slots",
                to="rooms.roomtype",
            ),
        ),
        (
            "tenant",
            models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="availability_slots",
                to="tenants.tenant",
            ),
        ),
    ],
    options={
        "db_table": "availability_slot",
        "indexes": [
            models.Index(
                condition=models.Q(("remaining__gt", 0)),
                fields=["tenant", "property", "room_type", "business_date"],
                name="availability_slot_ix_sellable",
            ),
            models.Index(
                fields=["room_type", "business_date"], name="availability_slot_ix_rt_date"
            ),
        ],
        "constraints": [
            models.UniqueConstraint(
                fields=("tenant", "property", "room_type", "channel", "business_date"),
                name="availability_slot_uq_tenant_property_roomtype_channel_date",
            ),
            models.CheckConstraint(
                condition=models.Q(("channel__in", ["direct"])),
                name="availability_slot_valid_channel",
            ),
            models.CheckConstraint(
                condition=models.Q(
                    ("total_units__gte", 0),
                    ("sold__gte", 0),
                    ("reserved__gte", 0),
                    ("blocked__gte", 0),
                    ("out_of_service__gte", 0),
                ),
                name="availability_slot_non_negative",
            ),
            models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_units__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("sold"), "+", models.F("reserved")
                                ),
                                "+",
                                models.F("blocked"),
                            ),
                            "+",
                            models.F("out_of_service"),
                        ),
                    )
                ),
                name="availability_slot_within_total",
            ),
        ],
    },
)

_POSTGRES_DDL_STATEMENTS = [
    'CREATE SEQUENCE "availability_slot_id_seq";',
    """
    CREATE TABLE "availability_slot" (
        "created_at" timestamp with time zone NOT NULL,
        "updated_at" timestamp with time zone NOT NULL,
        "tenant_id" bigint NOT NULL,
        "property_id" bigint NOT NULL,
        "room_type_id" bigint NOT NULL,
        "channel" varchar(16) NOT NULL DEFAULT 'direct',
        "business_date" date NOT NULL,
        "id" bigint NOT NULL,
        "total_units" integer NOT NULL,
        "sold" integer NOT NULL DEFAULT 0,
        "reserved" integer NOT NULL DEFAULT 0,
        "blocked" integer NOT NULL DEFAULT 0,
        "out_of_service" integer NOT NULL DEFAULT 0,
        "remaining" integer GENERATED ALWAYS AS
            ("total_units" - "sold" - "reserved" - "blocked" - "out_of_service") STORED,
        PRIMARY KEY ("business_date", "id"),
        CONSTRAINT "availability_slot_uq_tenant_property_roomtype_channel_date"
            UNIQUE ("tenant_id", "property_id", "room_type_id", "channel", "business_date"),
        CONSTRAINT "availability_slot_valid_channel" CHECK ("channel" IN ('direct')),
        CONSTRAINT "availability_slot_non_negative" CHECK (
            "total_units" >= 0 AND "sold" >= 0 AND "reserved" >= 0
            AND "blocked" >= 0 AND "out_of_service" >= 0
        ),
        CONSTRAINT "availability_slot_within_total" CHECK (
            "total_units" >= ("sold" + "reserved" + "blocked" + "out_of_service")
        ),
        CONSTRAINT "availability_slot_tenant_fk" FOREIGN KEY ("tenant_id")
            REFERENCES "tenant" ("id"),
        CONSTRAINT "availability_slot_property_fk" FOREIGN KEY ("property_id")
            REFERENCES "properties_property" ("id"),
        CONSTRAINT "availability_slot_room_type_fk" FOREIGN KEY ("room_type_id")
            REFERENCES "rooms_roomtype" ("id")
    ) PARTITION BY RANGE ("business_date");
    """,
    'ALTER SEQUENCE "availability_slot_id_seq" OWNED BY "availability_slot"."id";',
    'CREATE INDEX "availability_slot_ix_rt_date" ON "availability_slot" ("room_type_id", "business_date");',
    (
        'CREATE INDEX "availability_slot_ix_sellable" ON "availability_slot" '
        '("tenant_id", "property_id", "room_type_id", "business_date") WHERE "remaining" > 0;'
    ),
]


def _create_availability_slot_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        # NOTE: RunPython inside SeparateDatabaseAndState's database_operations
        # always receives the PRE-state app registry (Django passes
        # from_state.apps regardless of direction), which does not yet know
        # about AvailabilitySlot — the state_operations above are what teach
        # it that, but only to the migration's OWN state, not to this
        # callback. So this imports the real model directly rather than
        # `apps.get_model(...)`; safe here because this migration is
        # permanently tied to this exact model shape (any future schema
        # change is a NEW migration, never an edit to this one).
        from apps.availability.models import AvailabilitySlot

        schema_editor.create_model(AvailabilitySlot)
        return

    with schema_editor.connection.cursor() as cursor:
        for statement in _POSTGRES_DDL_STATEMENTS:
            cursor.execute(statement)

    # Bootstrap the starter partition set — the horizon AS OF migrate time.
    # The Celery task (apps/availability/tasks.py) keeps this rolling
    # forward afterwards; a migration is a one-time snapshot, not the
    # ongoing maintenance mechanism (roadmap E7).
    today = timezone.now().date()
    horizon = getattr(settings, "AVAILABILITY_HORIZON_DAYS", 400)
    with schema_editor.connection.cursor() as cursor:
        partitioning.ensure_partitions(
            start=today, end=today + timedelta(days=horizon), cursor=cursor
        )


def _drop_availability_slot_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        from apps.availability.models import AvailabilitySlot

        schema_editor.delete_model(AvailabilitySlot)
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS "availability_slot" CASCADE;')
        cursor.execute('DROP SEQUENCE IF EXISTS "availability_slot_id_seq";')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "properties",
            "0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more",
        ),
        ("rooms", "0004_remove_roomstateevent_room_state_event_valid_transition_and_more"),
        ("tenants", "0002_tenantsettings_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("released", "Released"),
                            ("picked_up", "Picked up"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inventory_blocks",
                        to="properties.property",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inventory_blocks",
                        to="rooms.roomtype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inventory_blocks",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_block",
            },
        ),
        migrations.CreateModel(
            name="InventoryBlockNight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nights",
                        to="availability.inventoryblock",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inventory_block_nights",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_block_night",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[_AVAILABILITY_SLOT_STATE],
            database_operations=[
                migrations.RunPython(
                    _create_availability_slot_table, _drop_availability_slot_table
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("direct", "Direct")], default="direct", max_length=16
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("percentage", "Percentage"),
                            ("pool", "Pool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "oversell_policy",
                    models.CharField(
                        choices=[("none", "None"), ("limited", "Limited")],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="channel_allocations",
                        to="properties.property",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="channel_allocations",
                        to="rooms.roomtype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="channel_allocations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "channel_allocation",
            },
        ),
        migrations.AddIndex(
            model_name="inventoryblock",
            index=models.Index(
                fields=["property", "room_type", "start_date", "end_date"],
                name="inventory_b_propert_8c28f8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryblock",
            constraint=models.UniqueConstraint(
                fields=("property", "name"), name="inventory_block_uq_property_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "confirmed", "released", "picked_up"])),
                name="inventory_block_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="inventory_block_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="inventory_block_end_on_or_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryblocknight",
            index=models.Index(fields=["business_date"], name="inventory_b_busines_bfc952_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryblocknight",
            constraint=models.UniqueConstraint(
                fields=("block", "business_date"), name="inventory_block_night_uq_block_date"
            ),
        ),
        migrations.AddIndex(
            model_name="channelallocation",
            index=models.Index(
                fields=["property", "room_type"], name="channel_all_propert_2da5ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["fixed", "percentage", "pool"])),
                name="channel_allocation_valid_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("oversell_policy__in", ["none", "limited"])),
                name="channel_allocation_valid_oversell_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)), name="channel_allocation_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="channel_allocation_end_on_or_after_start",
            ),
        ),
    ]
