# Generated by Django 5.2.17 on 2026-08-08 23:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(max_length=200)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'domain_event',
                'indexes': [models.Index(fields=['tenant_id', '-occurred_at'], name='domain_event_tenant_occurred'), models.Index(fields=['aggregate_type', 'aggregate_id', '-occurred_at'], name='domain_event_ix_aggregate'), models.Index(fields=['event_type', '-occurred_at'], name='domain_event_ix_type_occurred')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'event_id_uuid'), name='domain_event_uq_tenant_uuid'), models.CheckConstraint(condition=models.Q(('status__in', ['published', 'archived'])), name='domain_event_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('scope', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idempotency_record',
                'indexes': [models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='idempotency_record_ix_expires')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'scope', 'idempotency_key'), name='idempotency_record_uq_tenant_scope_key'), models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'completed'])), name='idempotency_record_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('event_type', models.CharField(max_length=200)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('dead_lettered', 'Dead-lettered')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='outbox_event_pending_created'), models.Index(condition=models.Q(('status', 'dead_lettered')), fields=['updated_at'], name='outbox_event_deadl_updated')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'published', 'dead_lettered'])), name='outbox_event_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='ProjectionState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projection_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_event_id', models.CharField(blank=True, default='', max_length=100)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('stalled', 'Stalled')], default='active', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'projection_state',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'failed', 'stalled'])), name='projection_state_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='audit_log_ix_entity_occurred'), models.Index(fields=['actor_id', '-occurred_at'], name='audit_log_ix_actor'), models.Index(fields=['tenant_id', '-occurred_at'], name='audit_log_ix_tenant')],
            },
        ),
    ]
