# Generated by Django 5.2.17 on 2026-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('prospective', 'Prospective'), ('active', 'Active'), ('suspended', 'Suspended'), ('decommissioned', 'Decommissioned')], default='prospective', max_length=20)),
                ('base_currency', models.CharField(max_length=3)),
                ('decommissioned_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'tenant',
                'db_table': 'tenant',
                'indexes': [models.Index(fields=['status'], name='tenant_ix_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['prospective', 'active', 'suspended', 'decommissioned'])), name='tenant_status_valid'), models.CheckConstraint(condition=models.Q(('base_currency__regex', '^[A-Z]{3}$')), name='tenant_base_currency_iso3')],
            },
        ),
    ]
