# Generated by Django 5.2.17 on 2026-08-09 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='settings', serialize=False, to='tenants.tenant')),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.PositiveBigIntegerField(db_index=True, editable=False)),
                ('flag_key', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'feature_flag',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'flag_key'), name='feature_flag_uq_tenant_key_active')],
            },
        ),
    ]
