# Generated by Django 5.2.17 on 2026-09-03 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenantsettings_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('primary_email', models.CharField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('closed', 'Closed')], default='active', max_length=16)),
                ('erasure_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_profiles', to='guests.guestprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guest_profiles', to='tenants.tenant')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.CharField(choices=[('room', 'Room'), ('lang', 'Language'), ('accessibility', 'Accessibility'), ('amenity', 'Amenity')], max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guest_preferences', to='tenants.tenant')),
                ('guest_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='guests.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('marketing', 'Marketing'), ('processing', 'Processing')], max_length=16)),
                ('basis', models.TextField()),
                ('granted_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='guest_consents', to='tenants.tenant')),
                ('guest_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consents', to='guests.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IdDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('doc_type', models.CharField(max_length=32)),
                ('ref_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('removed', 'Removed')], default='current', max_length=16)),
                ('guest_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_documents', to='guests.guestprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='id_documents', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['tenant', 'primary_email'], name='guests_gues_tenant__b66e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['tenant', 'primary_phone'], name='guests_gues_tenant__b50ecb_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'merged', 'closed'])), name='guest_profile_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='guestprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('erased_at__isnull', True), ('merged_into__isnull', True)), fields=('tenant', 'primary_email'), name='guest_profile_uq_tenant_email_active'),
        ),
        migrations.AddConstraint(
            model_name='guestprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('erased_at__isnull', True), ('merged_into__isnull', True)), fields=('tenant', 'primary_phone'), name='guest_profile_uq_tenant_phone_active'),
        ),
        migrations.AddIndex(
            model_name='guestpreference',
            index=models.Index(fields=['guest_profile'], name='guests_gues_guest_p_c6ad88_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestpreference',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['room', 'lang', 'accessibility', 'amenity'])), name='guest_preference_valid_category'),
        ),
        migrations.AddConstraint(
            model_name='guestpreference',
            constraint=models.UniqueConstraint(fields=('guest_profile', 'category'), name='guest_preference_uq_profile_category'),
        ),
        migrations.AddIndex(
            model_name='guestconsent',
            index=models.Index(fields=['guest_profile', 'purpose', 'withdrawn_at'], name='guests_gues_guest_p_a125e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestconsent',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['marketing', 'processing'])), name='guest_consent_valid_purpose'),
        ),
        migrations.AddConstraint(
            model_name='guestconsent',
            constraint=models.UniqueConstraint(fields=('guest_profile', 'purpose', 'granted_at'), name='guest_consent_uq_profile_purpose_granted'),
        ),
        migrations.AddIndex(
            model_name='iddocument',
            index=models.Index(fields=['guest_profile'], name='guests_iddo_guest_p_391873_idx'),
        ),
        migrations.AddConstraint(
            model_name='iddocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['current', 'expired', 'removed'])), name='id_document_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='iddocument',
            constraint=models.UniqueConstraint(fields=('guest_profile', 'doc_type', 'ref_hash'), name='id_document_uq_profile_type_hash'),
        ),
    ]
