# Generated by Django 5.2.17 on 2026-09-17 21:09

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        (
            "properties",
            "0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more",
        ),
        ("rooms", "0004_remove_roomstateevent_room_state_event_valid_transition_and_more"),
        ("tenants", "0002_tenantsettings_featureflag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HousekeepingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("business_date", models.DateField()),
                (
                    "task_kind",
                    models.CharField(
                        choices=[
                            ("departure", "Departure"),
                            ("daily", "Daily"),
                            ("defect", "Defect"),
                            ("deep_clean", "Deep Clean"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("planned", "Planned"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("quality_check", "Quality Check"),
                            ("verified", "Verified"),
                            ("defect", "Defect"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="housekeeping_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="housekeeping_tasks",
                        to="bookings.bookingline",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="housekeeping_tasks",
                        to="properties.property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="housekeeping_tasks",
                        to="rooms.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="housekeeping_tasks",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_task",
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(choices=[("pass", "Pass"), ("fail", "Fail")], max_length=8),
                ),
                (
                    "housekeeping_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inspections",
                        to="housekeeping.housekeepingtask",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inspections",
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inspections",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "inspection",
            },
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["assignee", "status", "business_date"], name="hk_task_ix_assignee"
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["property", "business_date"], name="hk_task_ix_property_date"
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(fields=["room", "business_date"], name="hk_task_ix_room_date"),
        ),
        migrations.AddConstraint(
            model_name="housekeepingtask",
            constraint=models.UniqueConstraint(
                fields=("room", "business_date", "task_kind"), name="hk_task_uq_room_date_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="housekeepingtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("task_kind__in", ["departure", "daily", "defect", "deep_clean"])
                ),
                name="hk_task_valid_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="housekeepingtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "planned",
                            "assigned",
                            "in_progress",
                            "quality_check",
                            "verified",
                            "defect",
                        ],
                    )
                ),
                name="hk_task_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(
                fields=("housekeeping_task",), name="inspection_uq_housekeeping_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("result__in", ["pass", "fail"])), name="inspection_valid_result"
            ),
        ),
    ]
