# Generated by Django 5.2.17 on 2026-09-18 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('housekeeping', '0001_initial'),
        ('properties', '0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more'),
        ('rooms', '0004_remove_roomstateevent_room_state_event_valid_transition_and_more'),
        ('tenants', '0002_tenantsettings_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['status', '-business_date'], name='hk_task_ix_status_date'),
        ),
    ]
