# Generated by Django 5.2.17 on 2026-09-02 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more'),
        ('tenants', '0002_tenantsettings_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('cancellation', 'Cancellation'), ('refund', 'Refund'), ('deposit', 'Deposit'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('cleaning', 'Cleaning'), ('pricing', 'Pricing')], max_length=16)),
                ('version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyEvaluationLog',
            fields=[
                ('evaluated_at', models.DateTimeField()),
                ('id', models.BigIntegerField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('pk', models.CompositePrimaryKey('evaluated_at', 'id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='policies.policy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'policy_type', 'status'], name='policies_po_tenant__2c4d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'policy_type', 'effective_from'], name='policies_po_tenant__b19c27_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__lt', models.F('effective_to')), _connector='OR'), name='policy_effective_to_after_from'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0), ('version__isnull', True), _connector='OR'), name='policy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'retired'])), name='policy_valid_status'),
        ),
        migrations.AddIndex(
            model_name='policyevaluationlog',
            index=models.Index(fields=['policy', 'evaluated_at'], name='policies_po_policy__41e576_idx'),
        ),
        migrations.AddIndex(
            model_name='policyevaluationlog',
            index=models.Index(fields=['tenant', 'evaluated_at'], name='policies_po_tenant__d787f2_idx'),
        ),
    ]
