# Generated by Django 5.2.17 on 2026-09-17 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        (
            "properties",
            "0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more",
        ),
        ("rooms", "0004_remove_roomstateevent_room_state_event_valid_transition_and_more"),
        ("tenants", "0002_tenantsettings_featureflag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("override", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True, default="")),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("scores", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "booking_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="allocation_records",
                        to="bookings.bookingline",
                    ),
                ),
                (
                    "chosen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="allocation_records",
                        to="properties.property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="allocation_records",
                        to="rooms.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="allocation_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "allocation_record",
                "indexes": [
                    models.Index(
                        fields=["room", "-created_at"], name="alloc_record_ix_room_created"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking_line",), name="allocation_record_uq_booking_line"
                    )
                ],
            },
        ),
    ]
