# Generated by Django 5.2.17 on 2026-09-17 20:34

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guests", "0003_gin_index_guest_profile_name"),
        (
            "properties",
            "0003_rename_properties_b_property_4f5e6d_idx_properties__propert_80482c_idx_and_more",
        ),
        ("reservations", "0001_initial"),
        ("rooms", "0004_remove_roomstateevent_room_state_event_valid_transition_and_more"),
        ("tenants", "0002_tenantsettings_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_ref", models.CharField(max_length=32)),
                (
                    "aggregate_status",
                    django_fsm.FSMField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("quote", "Quote"),
                            ("pending_payment", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_house", "In House"),
                            ("checked_out", "Checked Out"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("early_departure", "Early Departure"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("total_minor_units", models.BigIntegerField()),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
                ("price_snapshot", models.JSONField(blank=True, default=dict)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("guest_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="guests.guestprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="properties.property",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking",
            },
        ),
        migrations.CreateModel(
            name="BookingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.PositiveSmallIntegerField()),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("quote", "Quote"),
                            ("pending_payment", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_house", "In House"),
                            ("checked_out", "Checked Out"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("early_departure", "Early Departure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lines",
                        to="bookings.booking",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_lines",
                        to="rooms.room",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="booking_lines",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "booking_line",
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property", "arrival_date", "aggregate_status"],
                name="booking_ix_prop_arr_status",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["guest_profile"], name="booking_ix_guest"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["created_at"], name="booking_ix_created"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("tenant", "booking_ref"), name="booking_uq_tenant_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("reservation",), name="booking_uq_reservation"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "aggregate_status__in",
                        [
                            "inquiry",
                            "quote",
                            "pending_payment",
                            "confirmed",
                            "checked_in",
                            "in_house",
                            "checked_out",
                            "completed",
                            "cancelled",
                            "no_show",
                            "early_departure",
                        ],
                    )
                ),
                name="booking_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_minor_units__gte", 0)), name="booking_total_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")), name="booking_currency_iso3"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("departure_date__gt", models.F("arrival_date"))),
                name="booking_departure_after_arrival",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingline",
            index=models.Index(fields=["booking"], name="booking_line_ix_booking"),
        ),
        migrations.AddIndex(
            model_name="bookingline",
            index=models.Index(
                condition=models.Q(
                    ("room__isnull", False),
                    models.Q(("status__in", ["cancelled", "completed"]), _negated=True),
                ),
                fields=["room"],
                name="booking_line_ix_room_active",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingline",
            index=models.Index(
                condition=models.Q(("status__in", ["confirmed", "checked_in"])),
                fields=["arrival_date", "status"],
                name="booking_line_ix_arrivals",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingline",
            constraint=models.UniqueConstraint(
                fields=("booking", "line_no"), name="booking_line_uq_booking_lineno"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "inquiry",
                            "quote",
                            "pending_payment",
                            "confirmed",
                            "checked_in",
                            "in_house",
                            "checked_out",
                            "completed",
                            "cancelled",
                            "no_show",
                            "early_departure",
                        ],
                    )
                ),
                name="booking_line_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingline",
            constraint=models.CheckConstraint(
                condition=models.Q(("departure_date__gt", models.F("arrival_date"))),
                name="booking_line_departure_after_arrival",
            ),
        ),
    ]
