# Generated by Django 5.2.17 on 2026-08-10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_types', to='tenants.tenant')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('max_occupancy', models.PositiveSmallIntegerField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='tenants.tenant')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='rooms.roomtype')),
                ('code', models.CharField(max_length=32)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='properties.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='properties.floor')),
                ('operational_state', models.CharField(choices=[('vacant_clean', 'Vacant Clean'), ('vacant_dirty', 'Vacant Dirty'), ('occupied_clean', 'Occupied Clean'), ('occupied_dirty', 'Occupied Dirty'), ('out_of_service', 'Out of Service'), ('out_of_order', 'Out of Order'), ('cleaning', 'Cleaning'), ('inspected', 'Inspected')], default='vacant_clean', max_length=32)),
                ('current_booking_line_id', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_state_events', to='tenants.tenant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='state_events', to='rooms.room')),
                ('from_state', models.CharField(max_length=32)),
                ('to_state', models.CharField(max_length=32)),
                ('transition', models.CharField(choices=[('allocate', 'Allocate'), ('checkout', 'Checkout'), ('clean', 'Clean'), ('complete_cleaning', 'Complete Cleaning'), ('approve', 'Approve'), ('reject', 'Reject'), ('defect', 'Defect'), ('maintenance', 'Maintenance'), ('restore', 'Restore'), ('service', 'Service')], max_length=32)),
                ('actor_id', models.BigIntegerField()),
                ('actor_type', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='room_connections', to='tenants.tenant')),
                ('room_a', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connections_as_a', to='rooms.room')),
                ('room_b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connections_as_b', to='rooms.room')),
                ('connection_type', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_room_type_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'retired'])), name='room_type_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_room_code_per_property'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('operational_state__in', ['vacant_clean', 'vacant_dirty', 'occupied_clean', 'occupied_dirty', 'out_of_service', 'out_of_order', 'cleaning', 'inspected'])), name='room_valid_operational_state'),
        ),
        migrations.AddConstraint(
            model_name='roomstateevent',
            constraint=models.CheckConstraint(check=models.Q(('transition__in', ['allocate', 'checkout', 'clean', 'complete_cleaning', 'approve', 'reject', 'defect', 'maintenance', 'restore', 'service'])), name='room_state_event_valid_transition'),
        ),
        migrations.AddConstraint(
            model_name='roomconnection',
            constraint=models.UniqueConstraint(fields=('room_a', 'room_b'), name='unique_room_connection_pair'),
        ),
        migrations.AddConstraint(
            model_name='roomconnection',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, room_a=models.F('room_b')), name='room_connection_no_self_loop'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['tenant', 'status'], name='rooms_room_t_tenant_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property'], name='rooms_room_property_2b3c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='rooms_room_room_typ_3c4d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(condition=models.Q(('operational_state', 'vacant_clean')), fields=['room_type', 'id'], name='room_vacant_clean_candidates_idx'),
        ),
        migrations.AddIndex(
            model_name='roomstateevent',
            index=models.Index(fields=['room'], name='rooms_room_room_id_4d5e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='roomstateevent',
            index=models.Index(fields=['created_at'], name='rooms_room_created_5e6f7g_idx'),
        ),
        migrations.AddIndex(
            model_name='roomconnection',
            index=models.Index(fields=['room_a'], name='rooms_room_room_a_6f7g8h_idx'),
        ),
        migrations.AddIndex(
            model_name='roomconnection',
            index=models.Index(fields=['room_b'], name='rooms_room_room_b_7g8h9i_idx'),
        ),
    ]