# Generated by Django 5.2.17 on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # RoomType RLS
                """
                CREATE POLICY room_type_tenant_isolation_policy ON rooms_roomtype
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # Room RLS
                """
                CREATE POLICY room_tenant_isolation_policy ON rooms_room
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # RoomStateEvent RLS
                """
                CREATE POLICY room_state_event_tenant_isolation_policy ON rooms_roomstateevent
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
                # RoomConnection RLS
                """
                CREATE POLICY room_connection_tenant_isolation_policy ON rooms_roomconnection
                USING (tenant_id = current_setting('app.current_tenant_id')::bigint);
                """,
            ],
            reverse_sql=[
                "DROP POLICY IF EXISTS room_type_tenant_isolation_policy ON rooms_roomtype;",
                "DROP POLICY IF EXISTS room_tenant_isolation_policy ON rooms_room;",
                "DROP POLICY IF EXISTS room_state_event_tenant_isolation_policy ON rooms_roomstateevent;",
                "DROP POLICY IF EXISTS room_connection_tenant_isolation_policy ON rooms_roomconnection;",
            ],
        ),
    ]