# Generated by Django 5.2.17 on 2026-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rls'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='room',
            new_name='rooms_room_propert_0912a9_idx',
            old_name='rooms_room_property_2b3c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='rooms_room_room_ty_fe718b_idx',
            old_name='rooms_room_room_typ_3c4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='room_vacant_clean_idx',
            old_name='room_vacant_clean_candidates_idx',
        ),
        migrations.RenameIndex(
            model_name='roomconnection',
            new_name='rooms_roomc_room_a__985227_idx',
            old_name='rooms_room_room_a_6f7g8h_idx',
        ),
        migrations.RenameIndex(
            model_name='roomconnection',
            new_name='rooms_roomc_room_b__7da3f2_idx',
            old_name='rooms_room_room_b_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='roomstateevent',
            new_name='rooms_rooms_room_id_152e51_idx',
            old_name='rooms_room_room_id_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='roomstateevent',
            new_name='rooms_rooms_created_6dc645_idx',
            old_name='rooms_room_created_5e6f7g_idx',
        ),
        migrations.RenameIndex(
            model_name='roomtype',
            new_name='rooms_roomt_tenant__0cbc39_idx',
            old_name='rooms_room_t_tenant_1a2b3c_idx',
        ),
    ]
