# Generated by Django 5.2.17 on 2026-08-13 14:36

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_rooms_room_property_2b3c4d_idx_rooms_room_propert_0912a9_idx_and_more'),
        ('tenants', '0002_tenantsettings_featureflag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomstateevent',
            name='room_state_event_valid_transition',
        ),
        migrations.AlterField(
            model_name='room',
            name='operational_state',
            field=django_fsm.FSMField(choices=[('vacant_clean', 'Vacant Clean'), ('vacant_dirty', 'Vacant Dirty'), ('occupied_clean', 'Occupied Clean'), ('occupied_dirty', 'Occupied Dirty'), ('out_of_service', 'Out of Service'), ('out_of_order', 'Out of Order'), ('cleaning', 'Cleaning'), ('inspected', 'Inspected')], default='vacant_clean', max_length=32),
        ),
        migrations.AlterField(
            model_name='roomstateevent',
            name='transition',
            field=models.CharField(choices=[('allocate', 'Allocate'), ('checkout', 'Checkout'), ('clean', 'Clean'), ('complete_cleaning', 'Complete Cleaning'), ('approve', 'Approve'), ('reject', 'Reject'), ('defect', 'Defect'), ('maintenance', 'Maintenance'), ('restore', 'Restore'), ('restore_direct', 'Restore Direct'), ('service', 'Service'), ('service_complete', 'Service Complete')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='roomstateevent',
            constraint=models.CheckConstraint(condition=models.Q(('transition__in', ['allocate', 'checkout', 'clean', 'complete_cleaning', 'approve', 'reject', 'defect', 'maintenance', 'restore', 'restore_direct', 'service', 'service_complete'])), name='room_state_event_valid_transition'),
        ),
    ]
