# Generated by Django 5.2.17 on 2026-09-17 21:49

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guests", "0003_gin_index_guest_profile_name"),
        ("shared", "0003_enable_rls_accounts_tenancy"),
        ("tenants", "0002_tenantsettings_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("notification_type", models.CharField(max_length=64)),
                ("channel", models.CharField(max_length=16)),
                ("locale", models.CharField(default="en", max_length=16)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notification_templates",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notification_template",
            },
        ),
        migrations.CreateModel(
            name="NotificationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("notification_type", models.CharField(max_length=64)),
                ("channel", models.CharField(max_length=16)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("dead_lettered", "Dead-lettered"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "recipient_guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_jobs",
                        to="guests.guestprofile",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_jobs",
                        to="shared.domainevent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notification_jobs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "notification_job",
            },
        ),
        migrations.CreateModel(
            name="ChannelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=0, editable=False)),
                ("channel", models.CharField(max_length=16)),
                ("suppressed", models.BooleanField(default=False)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="channel_preferences",
                        to="guests.guestprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="channel_preferences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "channel_preference",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "guest_profile", "channel"),
                        name="chan_pref_uq_tenant_guest_channel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attempted", "Attempted"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, default="", max_length=200)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "notification_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="notifications.notificationjob",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_attempt",
                "indexes": [
                    models.Index(fields=["notification_job"], name="delivery_attempt_ix_job"),
                    models.Index(fields=["provider_ref"], name="delivery_attempt_ix_ref"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["attempted", "succeeded", "failed"])),
                        name="delivery_attempt_valid_status",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "notification_type", "channel", "locale"),
                name="notif_template_uq_type_channel_locale",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "retired"])),
                name="notif_template_valid_status",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationjob",
            index=models.Index(
                condition=models.Q(("status__in", ["pending", "delivering"])),
                fields=["status", "created_at"],
                name="notif_job_ix_relay_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationjob",
            index=models.Index(
                condition=models.Q(("status", "dead_lettered")),
                fields=["status", "updated_at"],
                name="notif_job_ix_dead_lettered",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationjob",
            index=models.Index(fields=["tenant", "created_at"], name="notif_job_ix_tenant_created"),
        ),
        migrations.AddConstraint(
            model_name="notificationjob",
            constraint=models.UniqueConstraint(
                fields=("source_event", "channel"), name="notif_job_uq_source_event_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "delivering", "delivered", "failed", "dead_lettered"],
                    )
                ),
                name="notif_job_valid_status",
            ),
        ),
    ]
